[package]
name = "eolina-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6"
clap = "2.34"
color-eyre = "0.5"
crossterm = "0.22"
thiserror = "1.0"
nom = "7.1"
