[package]
name = "eolina-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
crossterm = "0.22.1"
nom = "7.1.0"
